#########################################################
# +---------------------------------------------------+ #
# |                Bare Necessities                   | #
# +---------------------------------------------------+ #
#########################################################

# Version 1.0 SNAPSHOT
# If you have any issues join my Discord: https://discord.io/Larry2k

# To use special characters save this file as UTF-8, NOT ANSI.
# Take note of the following to avoid errors:
#   - NO tabs, YAML only allows spaces
#   - Correct indentation, YAML hierarchy is based entirely on indentation
#   - Escape all apostrophes in your text. E.g. instead of "can't", write "can''t"


#########################################################
#                      General                          #
#########################################################



#########################################################
#                Single Player Sleep                    #
#########################################################

enable-single-player-sleep: true

# Early time - 2300, Normal time - 0
early-wakeup-time: false

# Time to wait before time is changed. Recommended - 5
wakeup-delay: 5

# Broadcast random sleep messages when a player goes to sleep
random-sleep-messages: true
sleep-message-color: yellow


#########################################################
#                        Homes                          #
#########################################################

# Set to true to enable per-world permissions for teleporting to and creating homes
per-world-home-permissions: false

# Max homes a player can have
home-ranks:
  default: 1


#########################################################
#                       Economy                         #
#########################################################

# Balance new players should start with
starting-balance: 0

# Defines a currency symbol to use
currency-symbol: £
